name: Interactive Code Review Bot

on:
  pull_request:
    types: [opened, synchronize] # Déclenché lorsqu'une PR est ouverte ou mise à jour

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Nécessaire pour commenter la PR

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Cloner le code de la PR
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Interactive Code Review Script
      env:
        # Variables nécessaires au script
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO_FULL_NAME: ${{ github.repository }}
      run: |
        python interactive_review.py
